<?php
// Calling the head tag with the default values 
include 'partials/head.php';
// Override the active class in the include 
$contactClass = ' ';
$phpClass = 'active';
$homeClass = ' ';
// Calling the navbar from a seperate file
include 'partials/navbar.php';
 ?>    
        <main>  
            <a class="cardButton backButton" href="./assignments.php"><< Back</a>
            <h1 class="titlePage">Assignments</h1>
            
            <div class="assignments">
                <h2>1.2.3</h2>
                <h3>0NF</h3>
                <ul>
                    <li><b>invoice_nr</b></li>
                    <li>invoice_date</li>
                    <li>customer_nr</li>
                    <li>customer_name</li>
                    <li>customer_street</li>
                    <li>customer_zip</li>
                    <li>customer_city</li>
                    <li>product_nr</li>
                    <li>product_description</li>
                    <li>product_price</li>
                    <li>product_amount</li>
                    <li>product_subtotal*</li>
                    <li>product_total*</li>
                </ul>
                
                <h3>1NF</h3>
                <ul>
                    <li><b>invoice_nr</b></li>
                    <li>invoice_date</li>
                    <li>customer_nr</li>
                    <li>customer_name</li>
                    <li>customer_street</li>
                    <li>customer_zip</li>
                    <li>customer_city</li>
                    <li><p></p></li>
                    <li><b>product_nr</b></li>
                    <li><b>invoice_nr</b></li>
                    <li>product_description</li>
                    <li>product_price</li>
                    <li>product_amount</li>
                </ul>
                <h3>2NF</h3>
                <ul>
                    <li><b>invoice_nr</b></li>
                    <li>invoice_date</li>
                    <li>customer_nr</li>
                    <li>customer_name</li>
                    <li>customer_street</li>
                    <li>customer_zip</li>
                    <li>customer_city</li>
                    <li><p></p></li>
                    <li><b>product_nr</b></li>
                    <li><b>invoice_nr</b></li>
                    <li>product_amount</li>
                    <li><p></p></li>
                    <li><b>product_nr</b></li>
                    <li>product_description</li>
                    <li>product_price</li>
                </ul>
                <h3>3NF</h3>
                <ul>
                    <li><b>invoice_nr</b></li>
                    <li>invoice_date</li>
                    <li>customer_nr</li>
                    <li><p></p></li>
                    <li><b>customer_nr</b></li>
                    <li>customer_name</li>
                    <li>customer_street</li>
                    <li>customer_zip</li>
                    <li>customer_city</li>
                    <li><p></p></li>
                    <li><b>product_nr</b></li>
                    <li><b>invoice_nr</b></li>
                    <li>product_amount</li>
                    <li><p></p></li>
                    <li><b>product_nr</b></li>
                    <li>product_description</li>
                    <li>product_price</li>
                </ul>
                <h3>Entity</h3>
                <ul>
                    <li><h4>Invoice:</h4></li>
                    <li><b>invoice_nr</b></li>
                    <li>invoice_date</li>
                    <li>customer_nr</li>
                    <li><h4>Customer:</h4></li>
                    <li><b>customer_nr</b></li>
                    <li>customer_name</li>
                    <li>customer_street</li>
                    <li>customer_zip</li>
                    <li>customer_city</li>
                    <li><h4>Order:</h4></li>
                    <li><b>product_nr</b></li>
                    <li><b>invoice_nr</b></li>
                    <li>product_amount</li>
                    <li><h4>Product:</h4></li>
                    <li><b>product_nr</b></li>
                    <li>product_description</li>
                    <li>product_price</li>
                </ul>
                <hr>
                <h3>0NF</h3>
                <ul>
                    <li><b>invoice_nr</b></li>
                    <li>invoice_date</li>
                    <li>patient_nr</li>
                    <li>patient_name</li>
                    <li>patient_street</li>
                    <li>patient_zip</li>
                    <li>patient_city</li>
                    <li>hour_code</li>
                    <li>hour_date</li>
                    <li>hour_description</li>
                    <li>hour_amount</li>
                    <li>supplies_code</li>
                    <li>supplies_date</li>
                    <li>supplies_description</li>
                    <li>supplies_price</li>
                    <li>supplies_amount</li>
                    <li>supplies_subtotal*</li>
                    <li>supplies_total*</li>
                </ul>
                <h3>1NF</h3>
                <ul>
                    <li><b>invoice_nr</b></li>
                    <li>invoice_date</li>
                    <li>patient_nr</li>
                    <li>patient_name</li>
                    <li>patient_street</li>
                    <li>patient_zip</li>
                    <li>patient_city</li>
                    <li><p></p></li>
                    <li><b>hour_code</b></li>
                    <li><b>invoice_nr</b></li>
                    <li>hour_date</li>
                    <li>hour_description</li>
                    <li>hour_amount</li>
                    <li><p></p></li>
                    <li><b>supplies_code</b></li>
                    <li><b>invoice_nr</b></li>
                    <li>supplies_date</li>
                    <li>supplies_description</li>
                    <li>supplies_price</li>
                    <li>supplies_amount</li>
                </ul>
                <h3>2NF</h3>
                <ul>
                    <li><b>invoice_nr</b></li>
                    <li>invoice_date</li>
                    <li>patient_nr</li>
                    <li>patient_name</li>
                    <li>patient_street</li>
                    <li>patient_zip</li>
                    <li>patient_city</li>
                    <li><p></p></li>
                    <li><b>hour_code</b></li>
                    <li>hour_date</li>
                    <li>hour_description</li>
                    <li><p></p></li>
                    <li><b>supplies_code</b></li>
                    <li>supplies_date</li>
                    <li>supplies_description</li>
                    <li>supplies_price</li>
                    <li><p></p></li>
                    <li><b>invoice_nr</b></li>
                    <li>supplies_code</li>
                    <li>supplies_amount</li>
                    <li><p></p></li>
                    <li><b>invoice_nr</b></li>
                    <li>hour_code</li>
                    <li>hour_amount</li>
                </ul>
                <h3>3NF</h3>
                <ul>
                    <li><b>invoice_nr</b></li>
                    <li>invoice_date</li>
                    <li>patient_nr</li>
                    <li><p></p></li>
                    <li><b>patient_nr</b></li>
                    <li>patient_name</li>
                    <li>patient_street</li>
                    <li>patient_zip</li>
                    <li>patient_city</li>
                    <li><p></p></li>
                    <li><b>hour_code</b></li>
                    <li>hour_date</li>
                    <li>hour_description</li>
                    <li><p></p></li>
                    <li><b>supplies_code</b></li>
                    <li>supplies_date</li>
                    <li>supplies_description</li>
                    <li>supplies_price</li>
                    <li><p></p></li>
                    <li><b>invoice_nr</b></li>
                    <li>supplies_code</li>
                    <li>supplies_amount</li>
                    <li><p></p></li>
                    <li><b>invoice_nr</b></li>
                    <li>hour_code</li>
                    <li>hour_amount</li>
                </ul>
                <h3>Entity</h3>
                <ul>
                    <li><h4>Invoice:</h4></li>
                    <li><b>invoice_nr</b></li>
                    <li>invoice_date</li>
                    <li>patient_nr</li>
                    <li><h4>Patient:</h4></li>
                    <li><b>patient_nr</b></li>
                    <li>patient_name</li>
                    <li>patient_street</li>
                    <li>patient_zip</li>
                    <li>patient_city</li>
                    <li><h4>Hour:</h4></li>
                    <li><b>hour_code</b></li>
                    <li>hour_date</li>
                    <li>hour_description</li>
                    <li><h4>Supply:</h4></li>
                    <li><b>supplies_code</b></li>
                    <li>supplies_date</li>
                    <li>supplies_description</li>
                    <li>supplies_price</li>
                    <li><h4>Supply_order:</h4></li>
                    <li><b>invoice_nr</b></li>
                    <li>supplies_code</li>
                    <li>supplies_amount</li>
                    <li><h4>Hour_registered:</h4></li>
                    <li><b>invoice_nr</b></li>
                    <li>hour_code</li>
                    <li>hour_amount</li>
                </ul>
                <hr>
                <h3>0NF</h3>
                <ul>
                    <li><b>invoice_no</b></li>
                    <li>invoice_date</li>
                    <li>client_no</li>
                    <li>client_name</li>
                    <li>client_street</li>
                    <li>client_zip</li>
                    <li>client_city</li>
                    <li>participant_no</li>
                    <li>participant_name</li>
                    <li>participant_address</li>
                    <li>participant_phone</li>
                    <li>participant_age</li>
                    <li>activity_code</li>
                    <li>activity_name</li>
                    <li>activity_price</li>
                    <li>activity_total*</li>
                    <li>invoice_total*</li>
                </ul>
                <h3>1NF</h3>
                <ul>
                    <li><b>invoice_no</b></li>
                    <li>invoice_date</li>
                    <li>client_no</li>
                    <li>client_name</li>
                    <li>client_street</li>
                    <li>client_zip</li>
                    <li>client_city</li>
                    <li><p></p></li>
                    <li><b>participant_no</b></li>
                    <li><b>invoice_no</b></li>
                    <li>participant_name</li>
                    <li>participant_address</li>
                    <li>participant_phone</li>
                    <li>participant_age</li>
                    <li><p></p></li>
                    <li><b>activity_code</b></li>
                    <li><b>participant_no</b></li>
                    <li>activity_name</li>
                    <li>activity_price</li>
                </ul>
                <h3>2NF</h3>
                <ul>
                    <li><b>invoice_no</b></li>
                    <li>invoice_date</li>
                    <li>client_no</li>
                    <li>client_name</li>
                    <li>client_street</li>
                    <li>client_zip</li>
                    <li>client_city</li>
                    <li><p></p></li>
                    <li><b>participant_no</b></li>
                    <li>participant_name</li>
                    <li>participant_address</li>
                    <li>participant_phone</li>
                    <li>participant_age</li>
                    <li><p></p></li>
                    <li><b>invoice_no</b></li>
                    <li>participant_no</li>
                    <li><p></p></li>
                    <li><b>activity_code</b></li>
                    <li>activity_name</li>
                    <li>activity_price</li>
                    <li><p></p></li>
                    <li><b>participant_no</b></li>
                    <li>activity_code</li>
                </ul>
                <h3>3NF</h3>
                <ul>
                    <li><b>invoice_no</b></li>
                    <li>invoice_date</li>
                    <li>client_no</li>
                    <li><p></p></li>
                    <li><b>client_no</b></li>
                    <li>client_name</li>
                    <li>client_street</li>
                    <li>client_zip</li>
                    <li>client_city</li>
                    <li><p></p></li>
                    <li><b>participant_no</b></li>
                    <li>participant_name</li>
                    <li>participant_address</li>
                    <li>participant_phone</li>
                    <li>participant_age</li>
                    <li><p></p></li>
                    <li><b>invoice_no</b></li>
                    <li>participant_no</li>
                    <li><p></p></li>
                    <li><b>activity_code</b></li>
                    <li>activity_name</li>
                    <li>activity_price</li>
                    <li><p></p></li>
                    <li><b>participant_no</b></li>
                    <li>activity_code</li>
                </ul>
                <h3>Entity</h3>
                <ul>
                    <li><h4>Invoice:</h4></li>
                    <li><b>invoice_no</b></li>
                    <li>invoice_date</li>
                    <li>client_no</li>
                    <li><h4>Client:</h4></li>
                    <li><b>client_no</b></li>
                    <li>client_name</li>
                    <li>client_street</li>
                    <li>client_zip</li>
                    <li>client_city</li>
                    <li><h4>Participant:</h4></li>
                    <li><b>participant_no</b></li>
                    <li>participant_name</li>
                    <li>participant_address</li>
                    <li>participant_phone</li>
                    <li>participant_age</li>
                    <li><h4>Sign_up:</h4></li>
                    <li><b>invoice_no</b></li>
                    <li>participant_no</li>
                    <li><h4>Activity:</h4></li>
                    <li><b>activity_code</b></li>
                    <li>activity_name</li>
                    <li>activity_price</li>
                    <li><h4>Planned_activity:</h4></li>
                    <li><b>participant_no</b></li>
                    <li>activity_code</li>
                </ul>
            </div>
        </main>
        <!-- Calling the footer from a seperate file -->
        <?php
        include 'partials/footer.php'; 
        ?>  
    </body>

</html>